kind: ethereum/contract
name: TransmutationV2Factory
network:
source:
  address: ""
  abi: TransmutationV2Factory
  startBlock:
mapping:
  kind: ethereum/events
  apiVersion: 0.0.3
  language: wasm/assemblyscript
  entities:
    - SummonTransmutation
  abis:
    - name: TransmutationV2Factory
      file: ./abis/TransmutationV2Factory.json
  eventHandlers:
    - event: SummonTransmutation(indexed address,indexed address,indexed address,string,address,address)
      handler: handleSummonTransmutation
  file: ./src/factory-mappings.ts
