kind: ethereum/contract
name: TransmutationTemplate
network:
source:
  abi: Transmutation
mapping:
  kind: ethereum/events
  apiVersion: 0.0.3
  language: wasm/assemblyscript
  file: ./src/transmutation-mappings.ts
  entities:
    - Transmutation
  abis:
    - name: Transmutation
      file: ./abis/Transmutation.json
  eventHandlers:
    - event: "Deploy(address,address,address,address)"
      handler: handleDeploy
