kind: ethereum/contract
name: TransmutationFactory
network:
source:
  address: ""
  abi: TransmutationFactory
  startBlock:
mapping:
  kind: ethereum/events
  apiVersion: 0.0.3
  language: wasm/assemblyscript
  entities:
    - Deployment
  abis:
    - name: TransmutationFactory
      file: ./abis/TransmutationFactory.json
  eventHandlers:
    - event: Deployment(address,address,address,address,address)
      handler: handleTransmutationDeployment
  file: ./src/factory-mappings.ts
