kind: ethereum/contract
name: WrapNZapFactory
network:
source:
  address: "" # TODO fill out after wrap and zap deploy
  abi: WrapNZapFactory
  startBlock: # TODO fill out after wrap and zap deploy
mapping:
  kind: ethereum/events
  apiVersion: 0.0.3
  language: wasm/assemblyscript
  entities:
    - WrapNZap
  abis:
    - name: WrapNZapFactory
      file: ./abis/WrapNZapFactory.json
  eventHandlers:
    - event: NewWrapNZap(address,address,address)
      handler: handleNewWrapNZap
  file: ./src/wrap-n-zap-mappings.ts
